-- 011_treasuries_and_allowances.sql — every event pays its own attendees.
--
-- WHY THIS EXISTS
--
-- One number in the environment, SPONSOR_AMOUNT_XRP, used to decide what an
-- empty wallet was sent at the desk. It was paid from the issuer, and a single
-- daily cap across the whole deployment decided when to stop. That fitted
-- "switch a wallet on so a badge can land". It does not fit what an event does
-- with the money now: hand EVERY attendee an allowance to spend at the event's
-- own vendors, with a different amount per event.
--
-- So each event gets:
--
--   * an allowance — what one attendee may spend (events.allowance_drops);
--   * a budget — the most its treasury may pay out in total (budget_drops);
--   * a treasury — a wallet of its own, generated by the server, whose seed is
--     sealed with TREASURY_MASTER_KEY before it is written here;
--   * a book of what it paid (allowances), one row per attendee.
--
-- The `sponsorship` table from 002/003 is left exactly as it was. It is the
-- record of what the issuer paid before this migration, and nothing reads it
-- any more.
--
-- Idempotent: safe to re-run.

-- ---------------------------------------------------------------------------
-- The two numbers an organiser sets per event
-- ---------------------------------------------------------------------------

-- Drops, as exact integers. Both are compared against sums, so never a float
-- and never numeric-with-scale.
ALTER TABLE events ADD COLUMN IF NOT EXISTS allowance_drops bigint NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS budget_drops    bigint NOT NULL DEFAULT 0;

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_allowance_drops_check;
ALTER TABLE events ADD  CONSTRAINT events_allowance_drops_check CHECK (allowance_drops >= 0);
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_budget_drops_check;
ALTER TABLE events ADD  CONSTRAINT events_budget_drops_check CHECK (budget_drops >= 0);

-- ---------------------------------------------------------------------------
-- One treasury per event
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS event_treasuries (
  -- One per event, and never reassigned. No ON DELETE: an event that paid
  -- people must not be deletable out from under the record of its wallet.
  event_id     integer     PRIMARY KEY REFERENCES events (event_id),

  -- Public. This is where the organiser sends XRP to fund the event.
  address      text        NOT NULL,

  -- The seed, sealed (AES-256-GCM) with TREASURY_MASTER_KEY and bound to this
  -- event id and address. Never decrypted except to sign one payment, never
  -- returned by any route, never logged. See src/treasury/seal.ts.
  sealed_seed  text        NOT NULL,

  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT event_treasuries_address_key UNIQUE (address),
  CONSTRAINT event_treasuries_sealed_seed_format CHECK (sealed_seed LIKE 'v1.%')
);

-- ---------------------------------------------------------------------------
-- What each treasury paid, and to whom
-- ---------------------------------------------------------------------------
--
-- TWO-PHASE, for the reason 003 gave: the row is written BEFORE the Payment is
-- submitted, so a lost race costs budget headroom rather than XRP.
--
--   reserve()  INSERT status='reserved', tx_hash NULL   (before the Payment)
--   confirm()  UPDATE status='confirmed', tx_hash       (Payment validated)
--   release()  DELETE the reservation                    (Payment never landed)
--
-- The budget is enforced by the INSERT itself, under an advisory lock taken on
-- the event id, so two desks paying the same event cannot both read the same
-- headroom. Reserved rows count against it: money in flight is money spent.

CREATE TABLE IF NOT EXISTS allowances (
  id                bigserial   PRIMARY KEY,
  event_id          integer     NOT NULL REFERENCES events (event_id),

  -- Verbatim base58. Never folded: classic addresses are case-sensitive.
  address           text        NOT NULL,

  -- What the attendee may spend, as the event had it set at the time.
  allowance_drops   bigint      NOT NULL CHECK (allowance_drops >= 0),
  -- What the server added so the allowance is actually spendable: the reserve
  -- the wallet was short of, plus a buffer for transaction fees.
  topup_drops       bigint      NOT NULL CHECK (topup_drops >= 0),
  -- The Payment's Amount. Stated, not derived at read time, and held to the
  -- sum of the two above by a CHECK so the three can never disagree.
  amount_drops      bigint      NOT NULL CHECK (amount_drops > 0),

  -- The treasury that paid. Kept on the row because reconciling a payment
  -- whose outcome was lost means searching THAT account's history.
  treasury_address  text        NOT NULL,

  status            text        NOT NULL DEFAULT 'reserved'
                                CHECK (status IN ('reserved', 'confirmed')),
  tx_hash           text,

  reserved_at       timestamptz NOT NULL DEFAULT now(),
  confirmed_at      timestamptz,

  CONSTRAINT allowances_amount_is_sum CHECK (amount_drops = allowance_drops + topup_drops),
  CONSTRAINT allowances_confirmed_has_hash CHECK (status <> 'confirmed' OR tx_hash IS NOT NULL),
  -- Once per attendee per event. A 23505 here is the expected outcome of a
  -- lost race, not an error.
  CONSTRAINT allowances_event_address_key UNIQUE (event_id, address),
  -- One Payment is one allowance. NULLs are distinct, so reservations coexist.
  CONSTRAINT allowances_tx_hash_key UNIQUE (tx_hash)
);

-- The budget SUM, and the console's per-event list.
CREATE INDEX IF NOT EXISTS allowances_event_idx ON allowances (event_id, id);
