-- 013_purchases.sql — who ordered what, and whether the ledger says they paid.
--
-- A purchase is written BEFORE anybody pays, as a reservation: it holds stock
-- so two phones cannot both buy the last unit, and it names the Payment that
-- will settle it (the id goes in the Payment's memo). The ledger decides the
-- rest — a purchase becomes `paid` only once a validated Payment from the buyer
-- to the vendor, for exactly the amount, carrying that memo, has been read back.
-- A vendor hands an item over only for a paid purchase.
--
-- The vendor sessions that open the order screen live here too. They are kept
-- apart from admin sessions (007) on purpose: nothing a vendor holds may ever be
-- something the admin guard could be persuaded to read.
--
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS purchases (
  -- A random uuid, generated by the server. Also the Payment's memo.
  id                uuid        PRIMARY KEY,

  event_id          integer     NOT NULL REFERENCES events (event_id),
  -- No ON DELETE: a vendor or an item somebody paid for cannot be deleted
  -- out from under the record of it. Hide it instead.
  vendor_id         bigint      NOT NULL REFERENCES vendors (id),
  item_id           bigint      NOT NULL REFERENCES vendor_items (id),

  buyer_address     text        NOT NULL,
  -- Where the Payment must go: the vendor's wallet when the order was placed.
  vendor_address    text        NOT NULL,
  -- Names as they were, so a later rename does not rewrite a receipt.
  vendor_name       text        NOT NULL,
  item_name         text        NOT NULL,

  quantity          integer     NOT NULL,
  unit_price_drops  bigint      NOT NULL,
  amount_drops      bigint      NOT NULL,

  status            text        NOT NULL DEFAULT 'reserved'
                                CHECK (status IN ('reserved', 'paid', 'expired')),
  xaman_uuid        text,
  tx_hash           text,

  created_at        timestamptz NOT NULL DEFAULT now(),
  -- After this an unpaid reservation stops holding stock.
  expires_at        timestamptz NOT NULL,
  paid_at           timestamptz,
  -- Set by the vendor when the item leaves the counter; clearable.
  handed_over_at    timestamptz,

  CONSTRAINT purchases_quantity_check CHECK (quantity > 0 AND quantity <= 100),
  CONSTRAINT purchases_price_check CHECK (unit_price_drops > 0),
  CONSTRAINT purchases_amount_check CHECK (amount_drops = unit_price_drops * quantity),
  CONSTRAINT purchases_paid_has_hash CHECK (status <> 'paid' OR tx_hash IS NOT NULL),
  CONSTRAINT purchases_handover_needs_payment CHECK (handed_over_at IS NULL OR status = 'paid'),
  -- One Payment pays for one order. NULLs are distinct.
  CONSTRAINT purchases_tx_hash_key UNIQUE (tx_hash)
);

-- Stock: units taken per item.
CREATE INDEX IF NOT EXISTS purchases_item_idx ON purchases (item_id, status);
-- A vendor's order screen, newest first.
CREATE INDEX IF NOT EXISTS purchases_vendor_idx ON purchases (vendor_id, created_at DESC);
-- A buyer's pass, and the open-reservation cap.
CREATE INDEX IF NOT EXISTS purchases_buyer_idx ON purchases (event_id, buyer_address, status);
-- The console's sales list.
CREATE INDEX IF NOT EXISTS purchases_event_idx ON purchases (event_id, created_at DESC);

CREATE TABLE IF NOT EXISTS vendor_sessions (
  -- sha256 of the cookie value, exactly as 007 stores admin sessions. The raw
  -- id is a bearer token and is never written anywhere.
  id              text        PRIMARY KEY,
  wallet_address  text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS vendor_sessions_expires_idx ON vendor_sessions (expires_at);
